name: Deploy Snow Test

on:
    push:

jobs:
  RaiseChange:
      name: RaiseChange
      runs-on: ubuntu-latest
      steps:     

        - name: sleep
          run: |
            sleep 300;
            
        - name: ServiceNow Change
          uses: ServiceNow/servicenow-devops-change@v6.0.0
          id: create
          with:
            devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            context-github: ${{ toJSON(github) }}
            job-name: 'RaiseChange'
            change-request: '{"setCloseCode":"true","autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","assignment_group":"a715cd759f2002002920bde8132e7018","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
            interval: '100'
            timeout: '3600'
            changeCreationTimeOut: '3600'
            abortOnChangeCreationFailure: true
            abortOnChangeStepTimeout: true
            deployment-gate: '{"environment":"test","jobName":"DeploySnowTest"}'  
        
        - name: Output of Change Creation
          run: echo "change-request-number = ${{ steps.create.outputs.change-request-number }}" >> $GITHUB_OUTPUT

  DeploySnowTest:
      name: "DeploySnowTest"
      runs-on: ubuntu-latest
      environment: "test"
      steps:
          - name: Echo
            run: |
              echo "its deployed"

